# Generated by Django 4.2 on 2025-05-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant'),
        ('scm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_unit', models.CharField(max_length=50)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scm.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='products.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_score', models.FloatField(default=0.0)),
                ('purchase_unit_score', models.FloatField(default=0.0)),
                ('suppler_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='scm.supplierproduct')),
            ],
        ),
    ]
