# Generated by Django 4.2 on 2025-05-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scm', '0002_supplierproduct_supplierproductscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproductscore',
            old_name='suppler_product',
            new_name='supplier_product',
        ),
    ]
