# Generated by Django 4.2 on 2025-05-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('max_stock', models.PositiveIntegerField(default=0)),
                ('bulk_unit', models.CharField(choices=[('grams', 'Grams'), ('kilograms', 'Kilograms'), ('units', 'Units'), ('meters', 'Meters')], default='units', max_length=10)),
                ('is_bulk', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
