# Generated by Django 4.2 on 2025-05-08 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scm', '0003_rename_suppler_product_supplierproductscore_supplier_product'),
        ('products', '0002_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequential_id', models.PositiveIntegerField()),
                ('purchaseprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('current_status', models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received in Warehouse'), ('quality_check', 'Quality Check'), ('ready_for_sale', 'Ready for Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('discarded', 'Discarded')], default='ordered', max_length=20)),
                ('status_changed', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('date_quality_check', models.DateTimeField(blank=True, null=True)),
                ('date_ready_for_sale', models.DateTimeField(blank=True, null=True)),
                ('date_reserved', models.DateTimeField(blank=True, null=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('date_shipped', models.DateTimeField(blank=True, null=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('date_discarded', models.DateTimeField(blank=True, null=True)),
                ('purchase_order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location_in_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quality_check_passed', models.BooleanField(blank=True, null=True)),
                ('quality_check_notes', models.TextField(blank=True, null=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.productvariant')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scm.supplier')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-status_changed'],
                'unique_together': {('product_variant', 'sequential_id')},
            },
        ),
    ]
