# Generated by Django 4.2 on 2025-05-09 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='purchaseprice',
            new_name='purchase_price',
        ),
    ]
